camunda.bpm.client:
  base-url: http://localhost:8080/engine-rest # the URL pointing to the Camunda Platform Runtime REST API
  lock-duration: 10000 # defines how many milliseconds the External Tasks are locked until they can be fetched again
  subscriptions:  
    changevalue: # This is topic name
      variable-names: name,age # only fetch these variables
      process-definition-key: siddhuexternaldelegate #this is the id that we give for process ID
camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
  filter:
    create: All tasks      